apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: starterapp
  name: starterapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: starterapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: starterapp
    spec:
      containers:
      - image: cagritasci/starterapp
        name: starterapp
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres:5432/postgres"
        - name: SPRING_DATSOURCE_USERNAME
          value: "postgres"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "mysecretpassword"
        resources: {}
status: {}
