version: "3.8"
services:
  postgresdb:
    image: postgres:14.19
    container_name: todopsql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - todonet
    volumes:
      - pgdata:/var/lib/postgresql/data

  starterapp:
    image: starterapp:v1
    build:
      context: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://todopsql:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: mysecretpassword
    ports:
      - "8080:8080"
    depends_on:
      - postgresdb
    networks:
      - todonet
  
  frontend:
    build: ../frontend    
    ports:
      - "3000:80"   # Our web is exposed on port 3000
    depends_on:
      - starterapp  # Backend must be running before frontend
    networks:
      - todonet     # Frontend is also on the same network

networks:
  todonet:
    name: todonet

volumes:
  pgdata:
